
server:
  port: 8001
  connection-timeout: 30
  tomcat:
    max-threads: 0
    uri-encoding: UTF-8

spring:
  datasource:
#    url: 'jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=utf-8&amp;tinyInt1isBit=false&amp;allowMultiQueries=true'
    #url: 'jdbc:mysql://localhost:3306/test'
    url: 'jdbc:mysql://192.168.32.201:3306/hzwcolatest'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 3
      

mybatis:
  mapper-locations:
  - classpath:mybatis/*.xml

